
project:
  type: website

website:
  title: "Cat Analytics"
#  favicon: /images/catgeo.svg
  
  navbar:
#    logo: "images/catgeo.png"
      
    left:
      - text: "Visual Analytics"
        menu:
        - text: "Exercise 1a"


      - text: "GeoSpatial"
        menu:
        - text: "Exercise 1"

 
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
