
project:
  type: website

website:
#  title: "Catlytics"
  favicon: /images/catgeo.svg
  
  navbar:
    logo: "images/catgeo.png"
      
    left:
      - text: "Visualisation"
        menu:
        - text: "Project 1"


      - text: "GeoSpatial"
        menu:
        - text: "2-Singapore Bus Passenger Travel Patterns (Nov 2025)"
          href: geospatial/proj_2-sg_bus/sg_bus.qmd
        - text: "3-Predictive Modeling for Singapore HDB Resale Prices (Dec 2025)"
          href: geospatial/proj_3-predict_hdb_resale/hdb_resale.qmd

    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
